# Generated by Django 2.2.6 on 2019-11-03 07:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tatha', '0003_auto_20191031_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sign',
            name='city',
            field=models.GenericIPAddressField(),
        ),
    ]
