# Generated by Django 2.2.6 on 2019-11-04 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tatha', '0004_auto_20191103_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('username', models.EmailField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('zip', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Sign',
        ),
    ]
