# Generated by Django 2.2.6 on 2019-11-04 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tatha', '0006_auto_20191104_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='zip',
            field=models.IntegerField(max_length=5),
        ),
    ]
