# Generated by Django 2.2.6 on 2019-11-04 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tatha', '0007_auto_20191104_0815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='fname',
            new_name='Fname',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='lname',
            new_name='Lname',
        ),
        migrations.AlterField(
            model_name='register',
            name='zip',
            field=models.IntegerField(),
        ),
    ]
